# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  push:
    tags:
      - "v*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  
env:
  # APP name
  APP_NAME: IceLiveViewer

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Build
        run: |
          flutter config --enable-windows-desktop
          flutter pub get
          flutter build windows
    
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: IceLiveViewer-${{github.ref_name}}-windows.zip
          directory: build/windows/runner/Release
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{github.ref_name}}
          draft: true
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            build/windows/runner/Release/IceLiveViewer-${{github.ref_name}}-windows.zip

      - name: Upload Release Asset
        uses: actions/upload-artifact@v3
        with:
          name: artifact-windows
          path: build/windows/runner/Release/IceLiveViewer-${{github.ref_name}}-windows.zip


  build-android:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Java to compile Android project
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Build
        run: |
          flutter pub get
          flutter build apk
    
      - name: Rename APK
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/IceLiveViewer-${{github.ref_name}}-android.apk
          
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{github.ref_name}}
          draft: true
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            build/app/outputs/flutter-apk/IceLiveViewer-${{github.ref_name}}-android.apk

      - name: Upload Release Asset
        uses: actions/upload-artifact@v3
        with:
          name: artifact-android
          path: build/app/outputs/flutter-apk/IceLiveViewer-${{github.ref_name}}-android.apk

